#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-stream/functions"

cmd-nginx-stream-show-config() {
  declare desc="display app nginx config"
  declare cmd="nginx-stream:show-config"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1"

  verify_app_name "$APP"
  if [[ ! -f "$DOKKU_ROOT/$APP/stream.conf" ]]; then
    dokku_log_fail "No stream.conf exists for $APP"
  fi

  cat "$DOKKU_ROOT/$APP/stream.conf"
}